### ISSUE TITLE
what about double / path in the router?

### ISSUE THREAD

**Issue by andreabisello** [creativetimofficial/vue-argon-dashboard#10]
Hi,
in the project i see, in the router.js file,
two object of route inside the routing array.
![image](https://user-images.githubusercontent.com/2149815/61303076-2dd92400-a7e7-11e9-8fe4-2f1eae7cfc8c.png)
what is this?
i'm not able to read anything about this in the documentation
how it should work?
thanks

**Comment by sajadevo** [comment]
Hi there,

We've released a newer version of the product and all of the issues are fixed.

All the best,
Sajad
