### ISSUE TITLE
Question: Nuxt

### ISSUE THREAD

**Issue by realrashid** [creativetimofficial/vue-argon-dashboard#13]
Hi @timcreative ,

I am try to use the dashboard with Nuxt i have implemented everythings except the SidebarPlugin,NotificationsPlugin.

I got bleow error.

```js
Cannot read property 'showSidebar' of undefined
```

In terminal i got bleow error.

`
ERROR  [Vue warn]: Property or method "$sidebar" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
`

**Comment by realrashid** [comment]
Hey i fix the issue.

The issue is with its plugin.

i just changed the argon-dashboard.js

From

```vue
import "@/assets/vendor/nucleo/css/nucleo.css";
import "@/assets/scss/argon.scss";
import globalComponents from "./globalComponents";
import globalDirectives from "./globalDirectives";
import SidebarPlugin from "@/components/SidebarPlugin/index"
import NotificationPlugin from "@/components/NotificationPlugin/index"

export default {
  install(Vue) {
    Vue.use(globalComponents);
    Vue.use(globalDirectives);
    Vue.use(SidebarPlugin);
    Vue.use(NotificationPlugin);
  }
};
```
To
``` vue
import Vue from 'vue'
import '@/assets/vendor/nucleo/css/nucleo.css'
import '@/assets/scss/argon.scss'
import globalComponents from './globalComponents'
import globalDirectives from './globalDirectives'
import SidebarPlugin from '@/components/SidebarPlugin/index'
import NotificationPlugin from '@/components/NotificationPlugin/index'

Vue.use(globalComponents)
Vue.use(globalDirectives)
Vue.use(SidebarPlugin)
Vue.use(NotificationPlugin)
```

After doing this its fixed that error and everythings starts working..

Thank for the great design system.

**Comment by vinayakkulkarni** [comment]
getting the same error
