### ISSUE TITLE
Modals not working

### ISSUE THREAD

**Issue by baristaGeek** [creativetimofficial/vue-argon-dashboard#14]
Just copy pasting the code that is in the docs. Am I missing something?

**Comment by zikalol** [comment]
modal0 of undefined error im getting when i try to use a modal

**Comment by fjdelahorra** [comment]
I´ve faced the same problem, but i fixed it adding to data method, this declaration, i guess must be mandatory declare a boolean variable for all modal you´ve got

data() {
...
modals: {
  modal0: false
}
...
}

**Comment by stevek-pro** [comment]
I had the same issue and fixed it with this code, but getting a new error, please investigate whomever it may concern and post updates here: 

```
  data: function() {
    let modals = {
      modal2: false
    }
    return {
      modals
    }
  },
```

This is the new error: 

`[Vue warn]: Unknown custom element: <modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

I hope to get past this to get that juicy modal magic. stay healthy
