### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by anandbaskaran** [creativetimofficial/vue-argon-dashboard#15]
The link to demo page  https://demos.creative-tim.com/vue-argon-dashboard/ is not working anymore.

![image](https://user-images.githubusercontent.com/6847984/63249872-9eea7c00-c26a-11e9-8343-10acb397a67a.png)

**Comment by edward01** [comment]
working fine with me

**Comment by anandbaskaran** [comment]
Now it is working goos.
