### ISSUE TITLE
Multi Level Navbar Item

### ISSUE THREAD

**Issue by yenket** [creativetimofficial/vue-argon-dashboard#23]
Does someone know the codes for multi level navigation to be used in argon vue dashboard? The navigation bar shown in demo is only single level.

**Comment by kingraphaii** [comment]
Came across [this snippet](https://codepen.io/CoderSquirrel/pen/qJMPqM) on CodePen. Check it out.

**Comment by yenket** [comment]
@kingraphaii thanks
