### ISSUE TITLE
Where are the favicons being injected?

### ISSUE THREAD

**Issue by danielalejandromatheus** [creativetimofficial/vue-argon-dashboard#25]
I'm trying to set up some favicons for the website, yet they're being ignored, after figuring out what was wrong, it turns out that the default favicon was being injected into the html head section AFTER what I declare in the index.html head myself. Is there any way I can overwrite it? I can't find where its being injected

**Comment by moranthomas** [comment]
I'm having this issue as well. Does anyone have any ideas?

**Comment by moranthomas** [comment]
Turns out that my Chrome was caching the favicon (was working on multiple projects at once). 
So a clear of the cache and closing the browser tab and restart is what worked for me

**Comment by moranthomas** [comment]
Also you can specify where the favicon is found in the vue.config.js file (as per this post:https://stackoverflow.com/questions/52684709/vue-index-html-favicon-issue)
