### ISSUE TITLE
Toggle buttons when it's on don't turn off

### ISSUE THREAD

**Issue by SASFMONTOYA** [creativetimofficial/vue-argon-dashboard#27]
Hello guy help me please !
I want to know how to fix it

**Invalid prop: type check failed for prop "value". Expected Boolean, got Event found in <BaseSwitch> at src/components/BaseSwitch.vue**

![image](https://user-images.githubusercontent.com/22794697/73463499-5a035f00-434b-11ea-8aa6-7591bbbe4752.png)

```html
<base-switch v-model="model.active"></base-switch>
```

**Comment by FabianMontoya** [comment]
I have the same problem

**Comment by nonybrighto** [comment]
Me too!

**Comment by rukaury** [comment]
Solution of nonybrighto above worked for me.
