### ISSUE TITLE
How to use nested Menu

### ISSUE THREAD

**Issue by iqbalme** [creativetimofficial/vue-argon-dashboard#28]
How to use nested menu? I see 'children' in the SidebarItem.vue but It doesn't work.

**Comment by young-altair** [comment]
> How to use nested menu? I see 'children' in the SidebarItem.vue but It doesn't work.

Have you found a solution to this problem?

**Comment by DrJfrost** [comment]
Still waiting for an example on this one :s

**Comment by dragosct10** [comment]
Hi, guys! Thanks for using our products. The nested child is a feature that is present in the PRO version. 

Regards,
Dragos
