### ISSUE TITLE
vue-argon-dashboard  with vue-argon-design-system  is possible

### ISSUE THREAD

**Issue by moh-slimani** [creativetimofficial/vue-argon-dashboard#4]
is there a way to put vue-argon-dashboard and vue-argon-design-system in one project, i want to use the langin page in vue-argon-design-system with the the dashboard

**Comment by zippy4** [comment]
Did you happen to find a way? I'm looking to accomplish the same.

**Comment by Mohamed-SM** [comment]
> Did you happen to find a way? I'm looking to accomplish the same.

not really, I'm still trying to make it work but so far not working

**Comment by leep0o** [comment]
I renamed the styles directory `custom` to `dashboard` and also `argon.scss` to `argon-dashboard.scss` and moved them

I moved all the Vue components from `argon-dashboard` to `vue-argon-design-system` directory.

Next, I moved to the directory `plugins` `argon-dashboard.js` file and the missing components in the `globalComponents.js list`.

Finally added to `main.js`:
```
import Vue from 'vue'
...
import Argon from './plugins/argon-kit'
import ArgonDashboard from './plugins/argon-dashboard'

Vue.use(Argon)
Vue.use(ArgonDashboard)
...
```

**Comment by josemrp** [comment]
You can use [multi-page](https://cli.vuejs.org/config/#pages) to put `vue-argon-dashboard` and `vue-argon-design-system` in one project.

Here is an example [https://github.com/josemrp/vue-argon-design-system](https://github.com/josemrp/vue-argon-design-system)
- I moved all src files of `vue-argon-dashboard` and `vue-argon-design-system` inside the src folder.
- I moved and renamed the `public/index.html` of dashboard to `public/dashboard.html`
- Finally I added the `page` option in `vue.config.js`
