### ISSUE TITLE
no horizontal lines in line chart

### ISSUE THREAD

**Issue by Kvasha123** [creativetimofficial/vue-argon-dashboard#5]
hello there,

i have tried to create a line chart like in the demos and it works except for the white-dot-horizontal lines (in the dark-blue chart).
I thought that the options for this would be in the /components/Charts/config.js.

My Code is the exact code like in the demo-example.

Or is there a npm package that i am missing?

I did install:
    npm install chart.js --save
    npm install vue-chartjs chart.js --save 

Thx in Advance

**Comment by sajadevo** [comment]
Hi there,

We've released a newer version of the product and all of the issues are fixed.

All the best,
Sajad
