### ISSUE TITLE
[Bug] No overflow for base-dropdown

### ISSUE THREAD

**Issue by moaazelsayed** [creativetimofficial/vue-argon-dashboard#50]
### Version
v1.0.0
### Reproduction link
https://jsfiddle.net/#&togetherjs=djMigpn4v4
### Operating System
Windows
### Device
Laptop
### Browser & Version
Version 85.0.4183.121 (Official Build) (64-bit)Chrome 
### Steps to reproduce
Click on dropdown button
it will overflow if there are many items in the list to be selected
### What is expected?
The dropdown is expected to overflow if it exceeds the view of the page instead of extending the page itself
### What is actually happening?
"<base-dropdown  class="text-center float-left">
   <base-button></base-button>
   <base-button v-for="option in options">{{option}}</base-button>
</base-dropdown>"

Using the base-dropdown I get stuck with scrolling through 100s of options and increasing the length of the page itself instead of overflow. There's currently no option for overflow and other solutions https://vuescrolljs.yvescoding.org/, https://github.com/JefferyLiang/vue-overflow-scroll and https://binaryify.github.io/vue-custom-scrollbar all don't work on this component. Is there any way i'm able to get overflow to work on this component?

---

**Comment by dragosct10** [comment]
Hi, @moaazelsayed! Thanks for using our products. Why you don't put on the dropdown div a fixed height with overflow: scroll; and then you can put how many items did you want there? 

Regards,
Dragos
