### ISSUE TITLE
[Bug] VueDevTool not working in dev mode

### ISSUE THREAD

**Issue by chourabieure** [creativetimofficial/vue-argon-dashboard#59]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/product/vue-argon-dashboard#
### Operating System
Ubunutu
### Device
Laptop
### Browser & Version
Chrome Version 87.0.4280.141 (Official Build) (64-bit)
### Steps to reproduce
Download the template
npm install
npm run serve

### What is expected?
VueDevTools showing on browser
### What is actually happening?
VueDevTools not showing on browser

---

**Comment by dragosct10** [comment]
Hi, @chourabieure! Thanks for using our products. This is an issue with Vue 3: https://github.com/vuejs/vue-next/issues/750

Regards,
Dragos

**Comment by chourabieure** [comment]
Hello, iam dont really understand your answer since iam using Vue 2

**Comment by dragosct10** [comment]
Hi @chourabieure! You put version 2.0.0 in your issue template and that version is the Vue 3. 

Regards,
Dragos

**Comment by a37h** [comment]
Hey! Still no support?
