### ISSUE TITLE
Question: bootstrap-vue not used

### ISSUE THREAD

**Issue by mstratman** [creativetimofficial/vue-argon-dashboard#6]
I see you have custom components that achieve similar results to (albeit simpler than) bootstrap-vue. e.g. [base-button](https://github.com/creativetimofficial/vue-argon-dashboard/blob/master/src/components/BaseButton.vue) vs [b-button](https://bootstrap-vue.js.org/docs/components/button/).

I also see bootstrap-vue was pulled in as a dependency in the [package.json](https://github.com/creativetimofficial/vue-argon-dashboard/blob/master/package.json#L13).

Was this intentional? i.e. any reason not to use the bootstrap-vue components instead?

**Comment by HasanMothaffar** [comment]
I was also confused by this. I searched the whole project directory for files that use this dependency, but I didn't find anything.

**Comment by sajadevo** [comment]
Hi there,

We've released a newer version of the product and all of the issues are fixed.

All the best,
Sajad
