### ISSUE TITLE
[Bug] JavaScript is not working

### ISSUE THREAD

**Issue by JoakimBrandt** [creativetimofficial/vue-argon-dashboard#7]
**Version**
0.1.0

**Reproduction link**
https://jsfiddle.net/a6dh28m5/

**Operating System**
Linux Ubuntu

**Browser & Version**
Chrome Latest

**Steps to reproduce**

1. Download the standard version of Vue Argon Dashboard, install packages 
2. Try to use any kind of JavaScript components, such as modals, pagination, popovers etc
3. See that none of those works, sadly. :(

**What is expected?**
I expected JavaScript objects to behave properly. I expect popovers to pop, modals to modal and paginations to paginate.

I noticed that Argon Dashboard free does not include many JS-files at all, so I tried to include files from the standard Argon site, but that did not work either..

I just want to be able to use Bootstrap, JQuery etc, but it won't let me.

**What is actually happening?**
Buttons and styles work perfectly, just not the JavaScript methods/commands.

**Comment by JoakimBrandt** [comment]
Manually installed all components,

Vue JS, Vue Bootstrap, JQuery etc and now everything works fine.

**Comment by N3R00** [comment]
Hello friend, I'm having the same error, when I finish and compile my app, I go up for hosting, it returns me an error that javascript is not enabled (but is). Can you help me?


vue-argon-dashboard version is 0.1.0
