### ISSUE TITLE
[Bug] not working on npm install

### ISSUE THREAD

**Issue by asifmalik-ba** [creativetimofficial/vue-argon-dashboard#73]
### Version
Latest
### Reproduction link
https://user-images.githubusercontent.com/72439725/134075474-6d00be50-f1d3-435b-982c-1b794724a5ef.png
### Operating System
Manjaro Latest
### Device
HP ZHAN 66 Pro A 14
### Browser & Version
Terminal, OMz
### Steps to reproduce
npm install 
### What is expected?
it should download all the dependencies according to package.json
### What is actually happening?
https://user-images.githubusercontent.com/72439725/134075474-6d00be50-f1d3-435b-982c-1b794724a5ef.png

Please reply to asif.cse14@gmail.com

---

**Comment by a37h** [comment]
@akislawek do you mind sharing your node and npm version? Nothing seems to help me install the latest version

**Comment by cfwvip** [comment]
非常令人讨厌的js包依赖，碎片化，作者可以开发轮子，不停的提升轮子，我们在造车，有轮子了就用好了，结果轮子上的轮胎没有更新，因为是个人开发者，各自开发环境不同，个人又不保证更新，所以问题很多。

**Comment by sajadevo** [comment]
Hi guys,

For solving this just run `npm i --legacy-peer-deps` and it will fix the entire issue.

All the best,
Sajad
