### ISSUE TITLE
How do you hide and show the modal via Javascript?

### ISSUE THREAD

**Issue by mudenho** [creativetimofficial/vue-argon-dashboard#83]
How do you hide and show the modal via Javascript?
```
let myModal
if (desc === 'short'){
   myModal = document.getElementById('shortDesc')
} else {
  myModal = document.getElementById('desc')
}
// eslint-disable-next-line no-undef
const modal = bootstrap.Modal.getInstance(myModal)
modal.show()
```
      
 Using the above I get an error:
 `Uncaught (in promise) ReferenceError: bootstrap is not defined`

**Comment by maisamaf** [comment]
Hey @mudenho 

The error is given because you have not imported the `bootstrap`. Try importing the `bootstrap` in your `script` and let me know how it goes.

Regards,
Maisam Afshar

**Comment by mudenho** [comment]
> Hey @mudenho
> 
> The error is given because you have not imported the `bootstrap`. Try importing the `bootstrap` in your `script` and let me know how it goes.
> 
> Regards, Maisam Afshar

Perfect. That worked. Thank you.
